apiVersion: apps/v1
kind: Deployment
metadata:
  name: advanced-risk-engine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: advanced-risk-engine
  template:
    metadata:
      labels:
        app: advanced-risk-engine
    spec:
      containers:
      - name: advanced-risk-engine
        image: maramohamed22/advanced-risk-engine:latest  # Replace with your Docker Hub image
        ports:
        - containerPort: 5000
