---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: advanced-risk-engine
spec:
  selector:
    app: advanced-risk-engine
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer